// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWZayHQuwa7jum13vxQDQynCVRgkU6It4',
    appId: '1:862046507104:android:b07fe3145b18f1baeaf305',
    messagingSenderId: '862046507104',
    projectId: 'mychatapplication-568cd',
    databaseURL: 'https://mychatapplication-568cd-default-rtdb.firebaseio.com',
    storageBucket: 'mychatapplication-568cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTYhGDRGRbqmiRP48OF2CPYZoePLqjxYU',
    appId: '1:862046507104:ios:498d3ad10006cbb9eaf305',
    messagingSenderId: '862046507104',
    projectId: 'mychatapplication-568cd',
    databaseURL: 'https://mychatapplication-568cd-default-rtdb.firebaseio.com',
    storageBucket: 'mychatapplication-568cd.firebasestorage.app',
    iosClientId: '862046507104-s25bdfrvedqkbfenonu9lel5nbg0mj2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

}