class AppTexts {
  static const String signInAccount = 'Sign in your account';
  static const String email = 'Email';
  static const hintText = 'ex: jon.smith@email.com';
  static const String password = 'Password';
  static const hintTextDot = '*********';
  static const signIn = 'SIGN IN';
  static const orSignInWith = 'or sign in with';
  static const dontHaveAccount = 'Don’t have an account? ';
  static const signUp = 'Sign up';
  static const name = 'Name';
  static const smith = 'ex: jon smith';
  static const exampleEmail = 'ex: jon.smith@email.com';
  static const confirmPassword = 'Confirm Password';
  static const understood = '  I understood the';
  static const terms = ' terms & policy';
  static const orSignUp = 'or sign up with';
  static const haveAccount = 'Have an account?';
  static const notRegistered = 'This user is not registered';
  static const travelUz = ' TravelUz';
  static const korea = ' Korea';
  static const antalia = 'Antalia';
  static const gavaya = 'Gavaya';
  static const mascow = 'Mascow';
  static const parij = 'Parij';
  static const pekin = 'Pekin';
  static const dubay = 'Dubay';
  static const travel = 'Travel';
}
